blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.blog, name='blog'),
    path('<int:blog_id>/', views.detail, name='detail'),

]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vizitka.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vizitka/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField('Название', max_length=100)
    task = models.TextField('Информация')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

vizitka/models.py
from django.db import models


class Viz(models.Model):
    title = models.CharField('Название', max_length=60)
    text = models.TextField('Описание')
    date = models.DateTimeField()
    photo = models.ImageField(upload_to='vizitka/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def blog(request):
    task = Blog.objects.order_by('-id')
    return render(request, 'blog/blog.html', {'tasks':task})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'id': blog})

vizitka/views.py
from django.shortcuts import render
from .models import Viz


def index(request):
    info = Viz.objects.order_by('-id')
    return render(request, 'vizitka/index.html', {'info':info})

blog/templates/blog/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body>
    <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'home' %}" class="nav-link px-2 text-secondary">Главная</a></li>
          <li><a href="{% url 'blog:blog' %}" class="nav-link px-2 text-white">Блог</a></li>
          <li><a href="#" class="nav-link px-2 text-white">Pricing</a></li>
          <li><a href="#" class="nav-link px-2 text-white">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
        </ul>



        <div class="text-end">
          <button type="button" class="btn btn-outline-light me-2">Login</button>
          <button type="button" class="btn btn-warning">Sign-up</button>
        </div>
      </div>
    </div>
  </header>
    {% block body  %}{% endblock %}
</body>
</html>

blog/templates/blog/blog.html
{% extends 'blog/base.html' %}

{% block title %}
Интересные cтатьи
{% endblock %}


    {% block body %}
    <h1>Интересные статьи</h1>
    <h2>Всего  постов {{ tasks.count }}</h2>
    {% for el in tasks %}
    <a href="{% url  'blog:detail' el.id %}"><h2>{{el.title}}</h2></a>
    <h4>{{el.task|truncatechars:30}}</h4>
    {{el.date}}
    {% endfor %}
    {% endblock %}

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% block title %}
{{id.title}}
{% endblock %}
{% block body  %}
<h1>{{id.title}}</h1>
<p class="mr-5">{{ id.task }}</p>
    {{ id.date }}<br>
    <a href="{% url 'blog:blog' %}"><button class="btn btn-warning">  Назад  </button></a>

{% endblock %}

vizitka/templates/vizitka/index.html
{% extends 'blog/base.html' %}
{% block title %}
Главная
{% endblock %}

{% block body %}
    <h1>Главная</h1>
    {% for el in info %}
    <h2>{{el.title}}</h2>
    <p>{{el.text}}</p>
    <img src="{{ el.photo.url }}">
    {{el.date}}
    {% if el.url %}
    <a href="{{el.url}}">Ссылка</a>
    {% else %}
    {% endif %}
    {% endfor %}

{% endblock %}